### ISSUE TITLE
Passing a reward address in CLI is broken

### ISSUE THREAD

**Issue by shanev** [public-awesome/stakebird#218]
```
posts:
- body_hash: xR4eVU+Fej7Y1CoTmuLbJi72+7r8Cw0GMGKV/1zKKHU=
  creator: stb1m9kzq50zjwsz5krk7sevfnsdg6mh2e4y6xneqx
  curating_end_time: "2020-10-22T17:29:36.341943332Z"
  post_id_hash: a4ayc/80/OGda4BO/1o/V0etpOqiLx1JwB5S3beHW0s=
  reward_account: stb1m9kzq50zjwsz5krk7sevfnsdg6mh2e4y6xneqx
  vendor_id: 1
```
I think the 
 `staked tx curating post 1 1 "post"`
 is broken if I pass a reward address It doesn't like it
if I skip it it works 
`staked tx curating post 1 1 "first post" --from validator --chain-id albatross-1`

**Comment by JakeHartnell** [comment]
Passing a reward address works for me:
```
staked keys add meow --keyring-backend test
staked tx curating post 1 1 "test" $(staked keys show meow -a --keyring-backend test) --from validator --keyring-backend test --chain-id localnet-1
```

If I then query the post, the reward address is correct:
```
➜  stakebird git:(fix-reward-address) ✗ staked query curating posts 1
posts:
- body_hash: n4bQgYhMfWWaL+qgxVrQFaO/TxsrC4Is0V1sFbDwCgg=
  creator: stb1esyzxsz3ax06tmactpt6axl50fcd3743ggn2lv
  curating_end_time: "2020-10-26T00:36:29.590844016Z"
  post_id_hash: a4ayc/80/OGda4BO/1o/V0etpOqiLx1JwB5S3beHW0s=
  reward_account: stb1pklgy3mgsuym3tfa93pnkg4323c0ksekn5q249
  vendor_id: 1
➜  stakebird git:(fix-reward-address) ✗ staked keys show meow -a --keyring-backend test
stb1pklgy3mgsuym3tfa93pnkg4323c0ksekn5q249
```

Not specifying reward address also leads to intended behavior:
```
staked tx curating post 1 2 "test 2" --from validator --keyring-backend test --chain-id localnet-1 
➜  stakebird git:(fix-reward-address) ✗ staked query curating post 1 2
post:
  body_hash: 3sLkvEmSMUqcmlG72FnhsIG3QXiBjFPBnRjW92H12AQ=
  creator: stb1esyzxsz3ax06tmactpt6axl50fcd3743ggn2lv
  curating_end_time: "2020-10-26T00:38:45.912454662Z"
  post_id_hash: 1HNeOiZeFu7gP1lxi5tdAwGcB9i2xR+Q2jpmbuwTqzU=
  reward_account: stb1esyzxsz3ax06tmactpt6axl50fcd3743ggn2lv
  vendor_id: 1

```

There is an error if the `from` address is missing. Not sure if there is more of an issue here. Am I missing something? 

Can add a PR updating the Cobra command usage prompt.
