### ISSUE TITLE
Saved a post with an empty creator somehow

### ISSUE THREAD

**Issue by shanev** [public-awesome/stakebird#236]
```
posts:
- body_hash: e3b0c44298fc1c149afbf4c8996fb92427ae41e4
  creator: ""
  curating_end_time: "2020-11-20T05:27:43Z"
  post_id: "1328819871417856003"
  reward_account: stb1hslpyqu639kjwufuhzn9depu6yx7tlugx5d2am
  vendor_id: 1
```
